-- Phase A: candidate profiles, credentials, and private resume storage.
--
-- Design notes
--  - candidate_profiles is 1:1 with auth.users. A user MAY hold multiple roles
--    (admin, employer org member, candidate) simultaneously; roles are
--    determined by the presence of rows in admin_profiles,
--    organization_members, and candidate_profiles respectively.
--  - candidate_credentials is an audit-friendly ledger: certifications,
--    role history, and education all live in one table, tagged by
--    credential_type. This avoids three near-identical tables while keeping
--    queries simple.
--  - Employers never have direct SELECT on candidate tables. They see
--    candidate data only through job_applications (Phase B), and only for
--    jobs owned by their org. This migration intentionally does NOT grant
--    employer access; that contract belongs to the applications migration.
--  - The resume bucket is private. Candidates own their own prefix. The
--    employer path for resumes is signed URLs generated by the server after
--    it validates org membership on the application record — not storage RLS.

-- ---------------------------------------------------------------------------
-- candidate_profiles
-- ---------------------------------------------------------------------------

create table if not exists public.candidate_profiles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  full_name text not null check (length(trim(full_name)) between 1 and 200),
  headline text check (headline is null or length(headline) <= 200),
  country_code text not null check (country_code in ('US', 'CA')),
  location_label text check (location_label is null or length(location_label) <= 200),
  work_auth_us text not null default 'none'
    check (work_auth_us in ('citizen', 'permanent_resident', 'visa_required', 'none')),
  work_auth_ca text not null default 'none'
    check (work_auth_ca in ('citizen', 'permanent_resident', 'visa_required', 'none')),
  years_experience_anaplan int not null default 0
    check (years_experience_anaplan between 0 and 40),
  open_to_remote boolean not null default true,
  open_to_hybrid boolean not null default true,
  open_to_onsite boolean not null default false,
  linkedin_url text check (linkedin_url is null or length(linkedin_url) <= 500),
  portfolio_url text check (portfolio_url is null or length(portfolio_url) <= 500),
  bio text check (bio is null or length(bio) <= 8000),
  resume_path text,
  resume_uploaded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists candidate_profiles_country_idx
  on public.candidate_profiles (country_code);

-- keep updated_at fresh
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists candidate_profiles_set_updated_at on public.candidate_profiles;
create trigger candidate_profiles_set_updated_at
  before update on public.candidate_profiles
  for each row execute procedure public.set_updated_at();

-- ---------------------------------------------------------------------------
-- candidate_credentials
-- ---------------------------------------------------------------------------

create table if not exists public.candidate_credentials (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  credential_type text not null
    check (credential_type in ('certification', 'role_history', 'education')),
  title text not null check (length(trim(title)) between 1 and 250),
  organization_name text check (organization_name is null or length(organization_name) <= 250),
  start_date date,
  end_date date,
  description text check (description is null or length(description) <= 2000),
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  constraint credential_date_order check (
    start_date is null or end_date is null or start_date <= end_date
  )
);

create index if not exists candidate_credentials_user_idx
  on public.candidate_credentials (user_id, credential_type, sort_order);

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------

alter table public.candidate_profiles enable row level security;
alter table public.candidate_credentials enable row level security;

-- candidates own their row
create policy "candidate_profiles_select_self"
  on public.candidate_profiles for select
  to authenticated
  using (user_id = auth.uid());

create policy "candidate_profiles_insert_self"
  on public.candidate_profiles for insert
  to authenticated
  with check (user_id = auth.uid());

create policy "candidate_profiles_update_self"
  on public.candidate_profiles for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy "candidate_profiles_delete_self"
  on public.candidate_profiles for delete
  to authenticated
  using (user_id = auth.uid());

-- admins get read/write across the board
create policy "candidate_profiles_select_admin"
  on public.candidate_profiles for select
  to authenticated
  using (exists (select 1 from public.admin_profiles ap where ap.user_id = auth.uid()));

create policy "candidate_profiles_update_admin"
  on public.candidate_profiles for update
  to authenticated
  using (exists (select 1 from public.admin_profiles ap where ap.user_id = auth.uid()))
  with check (exists (select 1 from public.admin_profiles ap where ap.user_id = auth.uid()));

create policy "candidate_profiles_delete_admin"
  on public.candidate_profiles for delete
  to authenticated
  using (exists (select 1 from public.admin_profiles ap where ap.user_id = auth.uid()));

-- candidate_credentials: same self / admin pattern
create policy "candidate_credentials_select_self"
  on public.candidate_credentials for select
  to authenticated
  using (user_id = auth.uid());

create policy "candidate_credentials_insert_self"
  on public.candidate_credentials for insert
  to authenticated
  with check (user_id = auth.uid());

create policy "candidate_credentials_update_self"
  on public.candidate_credentials for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy "candidate_credentials_delete_self"
  on public.candidate_credentials for delete
  to authenticated
  using (user_id = auth.uid());

create policy "candidate_credentials_select_admin"
  on public.candidate_credentials for select
  to authenticated
  using (exists (select 1 from public.admin_profiles ap where ap.user_id = auth.uid()));

create policy "candidate_credentials_update_admin"
  on public.candidate_credentials for update
  to authenticated
  using (exists (select 1 from public.admin_profiles ap where ap.user_id = auth.uid()))
  with check (exists (select 1 from public.admin_profiles ap where ap.user_id = auth.uid()));

create policy "candidate_credentials_delete_admin"
  on public.candidate_credentials for delete
  to authenticated
  using (exists (select 1 from public.admin_profiles ap where ap.user_id = auth.uid()));

-- ---------------------------------------------------------------------------
-- Helper: does the authed user hold a candidate profile?
-- ---------------------------------------------------------------------------

create or replace function public.has_candidate_profile()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from public.candidate_profiles cp where cp.user_id = auth.uid()
  );
$$;

revoke all on function public.has_candidate_profile() from public;
grant execute on function public.has_candidate_profile() to authenticated;

-- ---------------------------------------------------------------------------
-- Storage: private resume bucket + policies
--
-- Files are keyed by {user_id}/{uuid}.{ext}. Candidates own their own prefix.
-- Employer/admin reads are intentionally NOT granted here — employers will
-- receive time-limited signed URLs generated by the server after verifying
-- the request against job_applications (Phase B). This keeps storage RLS
-- simple and auditable while employer access is mediated at the app layer.
-- ---------------------------------------------------------------------------

insert into storage.buckets (id, name, public)
values ('candidate-resumes', 'candidate-resumes', false)
on conflict (id) do nothing;

create policy "resumes_candidate_select_own"
  on storage.objects for select
  to authenticated
  using (
    bucket_id = 'candidate-resumes'
    and (auth.uid())::text = (storage.foldername(name))[1]
  );

create policy "resumes_candidate_insert_own"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'candidate-resumes'
    and (auth.uid())::text = (storage.foldername(name))[1]
  );

create policy "resumes_candidate_update_own"
  on storage.objects for update
  to authenticated
  using (
    bucket_id = 'candidate-resumes'
    and (auth.uid())::text = (storage.foldername(name))[1]
  )
  with check (
    bucket_id = 'candidate-resumes'
    and (auth.uid())::text = (storage.foldername(name))[1]
  );

create policy "resumes_candidate_delete_own"
  on storage.objects for delete
  to authenticated
  using (
    bucket_id = 'candidate-resumes'
    and (auth.uid())::text = (storage.foldername(name))[1]
  );
